version: '3'

services:
    database:
        container_name: itscrmdev-database
        image: oxy-mysql8
        ports:
            - 3306:3306
            - 33060:33060
        restart: always
        environment:
            - MYSQL_USER=testdev
            - MYSQL_PASSWORD=testdev123
            - MYSQL_DATABASE=testdev
        volumes:
            - W:/ItsPossible/06_IT/0601_Dockerfiles/060102_Data/06010201_MySQL:/var/lib/mysql
        networks:
            itscrmdev-network:
                ipv4_address: 180.23.0.2

    web:
        container_name: itscrmdev-web
        image: oxy-php8.1
        ports:
            - 80:80
            - 9005:9005
        volumes:
            - .:/var/www/html
            - W:/ItsPossible/06_IT/0601_Dockerfiles/060101_Configurations/06010103_Configurations/0801010301_Apache:/etc/apache2/sites-available/
            - W:/ItsPossible/06_IT/0601_Dockerfiles/060101_Configurations/06010103_Configurations/0801010301_Apache:/etc/apache2/sites-enabled/
        restart: always
        environment:
            - VIRTUAL_HOST=dev.itscrmdev.local
        networks:
            itscrmdev-network:
                ipv4_address: 180.23.0.3
    jobs:
        container_name: itscrmdev-jobs
        image: redis
        ports:
            - 6379:6379
        volumes:
            - W:/ItsPossible/06_IT/0601_Dockerfiles/060102_Data/06010202_Redis:/data
        networks:
            itscrmdev-network:
                ipv4_address: 180.23.0.4


networks:
    itscrmdev-network:
        driver: bridge
        ipam:
            config:
                - subnet: "180.23.0.0/16"
                  gateway: "180.23.0.1"
