<?php

namespace App\Helpers\Interfaces;

interface AutomationInterface {

    const STATUS_RUNNING = "AUTOMATION::STATUS::RUNNING";
    const STATUS_WAITING = "AUTOMATION::STATUS::WAITING";
    const STATUS_STOPPED = "AUTOMATION::STATUS::STOPPED";

    const NOTIFICATION_ON = "AUTOMATION::NOTIFICATION::ON";
    const NOTIFICATION_OFF = "AUTOMATION::NOTIFICATION::OFF";

    const NOTIFICATION_TYPE_MAIL = "AUTOMATION::NOTIFICATION::MAIL";
    const NOTIFICATION_TYPE_ALERT = "AUTOMATION::NOTIFICATION::ALERT";
}
